config/routes.rb
PreduzecaDb::Application.routes.draw do
  resources :preduzece_telefon

  resources :preduzece

  resources :tip_telefona

  resources :status

  resources :mesto

  resources :delatnost

  root 'delatnost#index'
end

app/models/tip_telefona.rb
class TipTelefona
  include Mongoid::Document
  field :_id, type: Integer
  field :tip_telefona, type: String
end

app/controllers/tip_telefona_controller.rb
class TipTelefonaController < ApplicationController
  before_action :set_tip_telefona, only: [:show, :edit, :update, :destroy]

  # GET /tip_telefona
  # GET /tip_telefona.json
  def index
    @tip_telefona = TipTelefona.all
  end

  # GET /tip_telefona/1
  # GET /tip_telefona/1.json
  def show
  end

  # GET /tip_telefona/new
  def new
    @tip_telefona = TipTelefona.new
  end

  # GET /tip_telefona/1/edit
  def edit
  end

  # POST /tip_telefona
  # POST /tip_telefona.json
  def create
    @tip_telefona = TipTelefona.new(tip_telefona_params)

    respond_to do |format|
      if @tip_telefona.save
        format.html { redirect_to @tip_telefona, notice: 'Tip telefona was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tip_telefona }
      else
        format.html { render action: 'new' }
        format.json { render json: @tip_telefona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tip_telefona/1
  # PATCH/PUT /tip_telefona/1.json
  def update
    respond_to do |format|
      if @tip_telefona.update(tip_telefona_params)
        format.html { redirect_to @tip_telefona, notice: 'Tip telefona was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tip_telefona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tip_telefona/1
  # DELETE /tip_telefona/1.json
  def destroy
    @tip_telefona.destroy
    respond_to do |format|
      format.html { redirect_to tip_telefona_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip_telefona
      @tip_telefona = TipTelefona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_telefona_params
      params.require(:tip_telefona).permit(:_id, :tip_telefona)
    end
end

app/helpers/tip_telefona_helper.rb
module TipTelefonaHelper
end

app/views/tip_telefona/_form.html.erb
<%= form_for(@tip_telefona) do |f| %>
  <% if @tip_telefona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tip_telefona.errors.count, "error") %> prohibited this tip_telefona from being saved:</h2>

      <ul>
      <% @tip_telefona.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :_id %><br>
    <%= f.number_field :_id %>
  </div>
  <div class="field">
    <%= f.label :tip_telefona %><br>
    <%= f.text_field :tip_telefona %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tip_telefona/edit.html.erb
<h1>Editing tip_telefona</h1>

<%= render 'form' %>

<%= link_to 'Show', @tip_telefona %> |
<%= link_to 'Back', tip_telefona_index_path %>

app/views/tip_telefona/index.html.erb
<h1>Listing tip_telefona</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Tip telefona</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tip_telefona.each do |tip_telefona| %>
      <tr>
        <td><%= tip_telefona._id %></td>
        <td><%= tip_telefona.tip_telefona %></td>
        <td><%= link_to 'Show', tip_telefona %></td>
        <td><%= link_to 'Edit', edit_tip_telefona_path(tip_telefona) %></td>
        <td><%= link_to 'Destroy', tip_telefona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tip telefona', new_tip_telefona_path %>

app/views/tip_telefona/new.html.erb
<h1>New tip_telefona</h1>

<%= render 'form' %>

<%= link_to 'Back', tip_telefona_index_path %>

app/views/tip_telefona/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>:</strong>
  <%= @tip_telefona._id %>
</p>

<p>
  <strong>Tip telefona:</strong>
  <%= @tip_telefona.tip_telefona %>
</p>

<%= link_to 'Edit', edit_tip_telefona_path(@tip_telefona) %> |
<%= link_to 'Back', tip_telefona_index_path %>