config/routes.rb
PreduzecaDb::Application.routes.draw do
  resources :preduzece_telefon

  resources :preduzece

  resources :tip_telefona

  resources :status

  resources :mesto

  resources :delatnost

  root 'delatnost#index'
end

app/models/preduzece_telefon.rb
class PreduzeceTelefon
  include Mongoid::Document
  field :_id, type: Integer
  field :preduzece_id, type: Integer
  field :tip_telefona_id, type: Integer
  field :telefon, type: String

  belongs_to :tip_telefona
  belongs_to :preduzece
end

app/controllers/preduzece_telefon_controller.rb
class PreduzeceTelefonController < ApplicationController
  before_action :set_preduzece_telefon, only: [:show, :edit, :update, :destroy]

  # GET /preduzece_telefon
  # GET /preduzece_telefon.json
  def index
    @preduzece_telefon = PreduzeceTelefon.all
  end

  # GET /preduzece_telefon/1
  # GET /preduzece_telefon/1.json
  def show
  end

  # GET /preduzece_telefon/new
  def new
    @preduzece_telefon = PreduzeceTelefon.new
  end

  # GET /preduzece_telefon/1/edit
  def edit
  end

  # POST /preduzece_telefon
  # POST /preduzece_telefon.json
  def create
    @preduzece_telefon = PreduzeceTelefon.new(preduzece_telefon_params)

    respond_to do |format|
      if @preduzece_telefon.save
        format.html { redirect_to @preduzece_telefon, notice: 'Preduzece telefon was successfully created.' }
        format.json { render action: 'show', status: :created, location: @preduzece_telefon }
      else
        format.html { render action: 'new' }
        format.json { render json: @preduzece_telefon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preduzece_telefon/1
  # PATCH/PUT /preduzece_telefon/1.json
  def update
    respond_to do |format|
      if @preduzece_telefon.update(preduzece_telefon_params)
        format.html { redirect_to @preduzece_telefon, notice: 'Preduzece telefon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @preduzece_telefon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preduzece_telefon/1
  # DELETE /preduzece_telefon/1.json
  def destroy
    @preduzece_telefon.destroy
    respond_to do |format|
      format.html { redirect_to preduzece_telefon_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preduzece_telefon
      @preduzece_telefon = PreduzeceTelefon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preduzece_telefon_params
      params.require(:preduzece_telefon).permit(:_id, :preduzece_id, :tip_telefona_id, :telefon)
    end
end

app/helpers/preduzece_telefon_helper.rb
module PreduzeceTelefonHelper
end

app/views/preduzece_telefon/_form.html.erb
<%= form_for(@preduzece_telefon) do |f| %>
  <% if @preduzece_telefon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preduzece_telefon.errors.count, "error") %> prohibited this preduzece_telefon from being saved:</h2>

      <ul>
      <% @preduzece_telefon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :_id %><br>
    <%= f.number_field :_id %>
  </div>
  <div class="field">
    <%= f.label :preduzece_id %><br>
    <%= f.number_field :preduzece_id %>
  </div>
  <div class="field">
    <%= f.label :tip_telefona_id %><br>
    <%= f.number_field :tip_telefona_id %>
  </div>
  <div class="field">
    <%= f.label :telefon %><br>
    <%= f.text_field :telefon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preduzece_telefon/edit.html.erb
<h1>Editing preduzece_telefon</h1>

<%= render 'form' %>

<%= link_to 'Show', @preduzece_telefon %> |
<%= link_to 'Back', preduzece_telefon_index_path %>

app/views/preduzece_telefon/index.html.erb
<h1>Listing preduzece_telefon</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Preduzece</th>
      <th>Tip telefona</th>
      <th>Telefon</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @preduzece_telefon.each do |preduzece_telefon| %>
      <tr>
        <td><%= preduzece_telefon._id %></td>
        <td><%= preduzece_telefon.preduzece_id %></td>
        <td><%= preduzece_telefon.tip_telefona_id %></td>
        <td><%= preduzece_telefon.telefon %></td>
        <td><%= link_to 'Show', preduzece_telefon %></td>
        <td><%= link_to 'Edit', edit_preduzece_telefon_path(preduzece_telefon) %></td>
        <td><%= link_to 'Destroy', preduzece_telefon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preduzece telefon', new_preduzece_telefon_path %>

app/views/preduzece_telefon/new.html.erb
<h1>New preduzece_telefon</h1>

<%= render 'form' %>

<%= link_to 'Back', preduzece_telefon_index_path %>

app/views/preduzece_telefon/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>:</strong>
  <%= @preduzece_telefon._id %>
</p>

<p>
  <strong>Preduzece:</strong>
  <%= @preduzece_telefon.preduzece_id %>
</p>

<p>
  <strong>Tip telefona:</strong>
  <%= @preduzece_telefon.tip_telefona_id %>
</p>

<p>
  <strong>Telefon:</strong>
  <%= @preduzece_telefon.telefon %>
</p>

<%= link_to 'Edit', edit_preduzece_telefon_path(@preduzece_telefon) %> |
<%= link_to 'Back', preduzece_telefon_index_path %>