config/routes.rb
PreduzecaDb::Application.routes.draw do
  resources :preduzece_telefon

  resources :preduzece

  resources :tip_telefona

  resources :status

  resources :mesto

  resources :delatnost

  root 'delatnost#index'
end

app/models/mesto.rb
class Mesto
  include Mongoid::Document
  field :_id, type: Integer
  field :mesto, type: String
  field :izbor, type: Integer
end

app/controllers/mesto_controller.rb
class MestoController < ApplicationController
  before_action :set_mesto, only: [:show, :edit, :update, :destroy]

  # GET /mesto
  # GET /mesto.json
  def index
    @mesto = Mesto.all
  end

  # GET /mesto/1
  # GET /mesto/1.json
  def show
  end

  # GET /mesto/new
  def new
    @mesto = Mesto.new
  end

  # GET /mesto/1/edit
  def edit
  end

  # POST /mesto
  # POST /mesto.json
  def create
    @mesto = Mesto.new(mesto_params)

    respond_to do |format|
      if @mesto.save
        format.html { redirect_to @mesto, notice: 'Mesto was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mesto }
      else
        format.html { render action: 'new' }
        format.json { render json: @mesto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mesto/1
  # PATCH/PUT /mesto/1.json
  def update
    respond_to do |format|
      if @mesto.update(mesto_params)
        format.html { redirect_to @mesto, notice: 'Mesto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mesto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mesto/1
  # DELETE /mesto/1.json
  def destroy
    @mesto.destroy
    respond_to do |format|
      format.html { redirect_to mesto_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mesto
      @mesto = Mesto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mesto_params
      params.require(:mesto).permit(:_id, :mesto, :izbor)
    end
end

app/helpers/mesto_helper.rb
module MestoHelper
end

app/views/mesto/_form.html.erb
<%= form_for(@mesto) do |f| %>
  <% if @mesto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mesto.errors.count, "error") %> prohibited this mesto from being saved:</h2>

      <ul>
      <% @mesto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :_id %><br>
    <%= f.number_field :_id %>
  </div>
  <div class="field">
    <%= f.label :mesto %><br>
    <%= f.text_field :mesto %>
  </div>
  <div class="field">
    <%= f.label :izbor %><br>
    <%= f.number_field :izbor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mesto/edit.html.erb
<h1>Editing mesto</h1>

<%= render 'form' %>

<%= link_to 'Show', @mesto %> |
<%= link_to 'Back', mesto_index_path %>

app/views/mesto/index.html.erb
<h1>Listing mesto</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Mesto</th>
      <th>Izbor</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mesto.each do |mesto| %>
      <tr>
        <td><%= mesto._id %></td>
        <td><%= mesto.mesto %></td>
        <td><%= mesto.izbor %></td>
        <td><%= link_to 'Show', mesto %></td>
        <td><%= link_to 'Edit', edit_mesto_path(mesto) %></td>
        <td><%= link_to 'Destroy', mesto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mesto', new_mesto_path %>

app/views/mesto/new.html.erb
<h1>New mesto</h1>

<%= render 'form' %>

<%= link_to 'Back', mesto_index_path %>

app/views/mesto/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>:</strong>
  <%= @mesto._id %>
</p>

<p>
  <strong>Mesto:</strong>
  <%= @mesto.mesto %>
</p>

<p>
  <strong>Izbor:</strong>
  <%= @mesto.izbor %>
</p>

<%= link_to 'Edit', edit_mesto_path(@mesto) %> |
<%= link_to 'Back', mesto_index_path %>