config/routes.rb
PreduzecaDb::Application.routes.draw do
  resources :preduzece_telefon

  resources :preduzece

  resources :tip_telefona

  resources :status

  resources :mesto

  resources :delatnost

  root 'delatnost#index'
end

app/models/preduzece.rb
class Preduzece
  include Mongoid::Document
  field :_id, type: Integer
  field :delatnost_id, type: Integer
  field :mesto_id, type: Integer
  field :status_id, type: Integer
  field :id, type: Integer
  field :naziv, type: String
  field :post_broj, type: String
  field :adresa, type: String
  field :sajt, type: String
  field :napomena, type: String

  belongs_to :delatnost
  belongs_to :mesto

  has_many :preduzece_telefon
end

app/controllers/preduzece_controller.rb
class PreduzeceController < ApplicationController
  before_action :set_preduzece, only: [:show, :edit, :update, :destroy]

  # GET /preduzece
  # GET /preduzece.json
  def index
    @preduzece = Preduzece.all
  end

  # GET /preduzece/1
  # GET /preduzece/1.json
  def show
  end

  # GET /preduzece/new
  def new
    @preduzece = Preduzece.new
  end

  # GET /preduzece/1/edit
  def edit
  end

  # POST /preduzece
  # POST /preduzece.json
  def create
    @preduzece = Preduzece.new(preduzece_params)

    respond_to do |format|
      if @preduzece.save
        format.html { redirect_to @preduzece, notice: 'Preduzece was successfully created.' }
        format.json { render action: 'show', status: :created, location: @preduzece }
      else
        format.html { render action: 'new' }
        format.json { render json: @preduzece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preduzece/1
  # PATCH/PUT /preduzece/1.json
  def update
    respond_to do |format|
      if @preduzece.update(preduzece_params)
        format.html { redirect_to @preduzece, notice: 'Preduzece was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @preduzece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preduzece/1
  # DELETE /preduzece/1.json
  def destroy
    @preduzece.destroy
    respond_to do |format|
      format.html { redirect_to preduzece_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preduzece
      @preduzece = Preduzece.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preduzece_params
      params.require(:preduzece).permit(:_id, :delatnost_id, :mesto_id, :status_id, :id, :naziv, :post_broj, :adresa, :sajt, :napomena)
    end
end

app/helpers/preduzece_helper.rb
module PreduzeceHelper
end

app/views/preduzece/_form.html.erb
<%= form_for(@preduzece) do |f| %>
  <% if @preduzece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preduzece.errors.count, "error") %> prohibited this preduzece from being saved:</h2>

      <ul>
      <% @preduzece.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :_id %><br>
    <%= f.number_field :_id %>
  </div>
  <div class="field">
    <%= f.label :delatnost_id %><br>
    <%= f.number_field :delatnost_id %>
  </div>
  <div class="field">
    <%= f.label :mesto_id %><br>
    <%= f.number_field :mesto_id %>
  </div>
  <div class="field">
    <%= f.label :status_id %><br>
    <%= f.number_field :status_id %>
  </div>
  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :naziv %><br>
    <%= f.text_field :naziv %>
  </div>
  <div class="field">
    <%= f.label :post_broj %><br>
    <%= f.text_field :post_broj %>
  </div>
  <div class="field">
    <%= f.label :adresa %><br>
    <%= f.text_field :adresa %>
  </div>
  <div class="field">
    <%= f.label :sajt %><br>
    <%= f.text_field :sajt %>
  </div>
  <div class="field">
    <%= f.label :napomena %><br>
    <%= f.text_field :napomena %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preduzece/edit.html.erb
<h1>Editing preduzece</h1>

<%= render 'form' %>

<%= link_to 'Show', @preduzece %> |
<%= link_to 'Back', preduzece_index_path %>

app/views/preduzece/index.html.erb
<h1>Listing preduzece</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Delatnost</th>
      <th>Mesto</th>
      <th>Status</th>
      <th>Id</th>
      <th>Naziv</th>
      <th>Post broj</th>
      <th>Adresa</th>
      <th>Sajt</th>
      <th>Napomena</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @preduzece.each do |preduzece| %>
      <tr>
        <td><%= preduzece._id %></td>
        <td><%= preduzece.delatnost_id %></td>
        <td><%= preduzece.mesto_id %></td>
        <td><%= preduzece.status_id %></td>
        <td><%= preduzece.id %></td>
        <td><%= preduzece.naziv %></td>
        <td><%= preduzece.post_broj %></td>
        <td><%= preduzece.adresa %></td>
        <td><%= preduzece.sajt %></td>
        <td><%= preduzece.napomena %></td>
        <td><%= link_to 'Show', preduzece %></td>
        <td><%= link_to 'Edit', edit_preduzece_path(preduzece) %></td>
        <td><%= link_to 'Destroy', preduzece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preduzece', new_preduzece_path %>

app/views/preduzece/new.html.erb
<h1>New preduzece</h1>

<%= render 'form' %>

<%= link_to 'Back', preduzece_index_path %>

app/views/preduzece/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to 'Back', delatnost_path(@preduzece.delatnost_id), class: "btn btn-inverse btn-small" %>
</p>

<p>
  <strong>Naziv:</strong>
  <%= @preduzece.naziv %>
</p>

<p>
  <strong>Delatnost:</strong>
  <%= @preduzece.delatnost.delatnost %>
</p>

<p>
  <strong>Post broj:</strong>
  <%= @preduzece.post_broj %>
</p>

<p>
  <strong>Mesto:</strong>
  <%= @preduzece.mesto.mesto %>
</p>

<p>
  <strong>Status:</strong>
  <%= @preduzece.status_id %>
</p>

<p>
  <strong>Adresa:</strong>
  <%= @preduzece.adresa %>
</p>

<p>
  <strong>Sajt:</strong>
  <%= link_to @preduzece.sajt, "http://#{@preduzece.sajt}", target: "_blank" %>
</p>

<p>
  <strong>Telefoni:</strong>
  <ul>
    <% @preduzece.preduzece_telefon.each do |tel| %>
      <li><%= tel.telefon %> (<%= tel.tip_telefona.tip_telefona %>)</li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Napomena:</strong>
  <%= @preduzece.napomena %>
</p>